function buildFinalPdf(projectRoot)
%BUILDFINALPDF Compile report body, create a course cover, and prepend it.
% Requires xelatex in PATH. The generated final PDF is report.pdf.

if nargin < 1
    projectRoot = fileparts(fileparts(mfilename('fullpath')));
end

oldDir = pwd;
cleanup = onCleanup(@() cd(oldDir)); %#ok<NASGU>
cd(projectRoot);

if exist('report.pdf', 'file')
    copyfile('report.pdf', 'report_body_previous.pdf');
end

runCommand('xelatex -interaction=nonstopmode report.tex');
runCommand('xelatex -interaction=nonstopmode report.tex');
movefile('report.pdf', 'report_body.pdf', 'f');

writeCoverTex(projectRoot);
runCommand('xelatex -interaction=nonstopmode cover.tex');
writeMergeTex(projectRoot);
runCommand('xelatex -interaction=nonstopmode merge_report.tex');
movefile('merge_report.pdf', 'report.pdf', 'f');
fprintf('Final PDF written to %s\n', fullfile(projectRoot, 'report.pdf'));
end

function runCommand(commandText)
[status, output] = system(commandText);
if status ~= 0
    error('Command failed: %s\n%s', commandText, output);
end
end

function writeCoverTex(projectRoot)
content = [
"\documentclass[UTF8,a4paper,12pt]{ctexart}" newline ...
"\usepackage{geometry}" newline ...
"\geometry{left=2.8cm,right=2.8cm,top=2.8cm,bottom=2.8cm}" newline ...
"\pagestyle{empty}" newline ...
"\begin{document}" newline ...
"\begin{center}" newline ...
" \vspace*{0.1cm}" newline ...
"{\Large 评分：\underline{\hspace{4cm}}}\hfill" newline ...
"\vspace{0.75cm}" newline ...
"{\Huge\bfseries SHANGHAI UNIVERSITY\\[0.45cm]}" newline ...
"{\zihao{1}\bfseries 课程论文\\[0.25cm]}" newline ...
"{\Large COURSE PAPER\\[1.05cm]}" newline ...
"{\zihao{2}\bfseries \parbox{0.82\textwidth}{\centering 基于 MATLAB 的高维混沌系统长期预测建模}\\[1.15cm]}" newline ...
"\end{center}" newline ...
"\zihao{4}" newline ...
" \renewcommand{\arraystretch}{1.18}" newline ...
"\begin{tabular}{rl}" newline ...
"课程名称： & 人工智能导论 \\[0.28cm]" newline ...
"组\quad 长： & 钟兴涛\quad 学号：25120617 \\[0.28cm]" newline ...
"组\quad 员： & 唐亦明\quad 学号：25120638 \\[0.20cm]" newline ...
"          & 戴云天\quad 学号：25120636 \\[0.20cm]" newline ...
"          & 任宇航\quad 学号：25120699 \\[0.20cm]" newline ...
"          & 黄宇轩\quad 学号：25120619 \\[0.28cm]" newline ...
"打印日期： & \today \\[0.28cm]" newline ...
"教师评分： & \underline{\hspace{5cm}} \\[0.28cm]" newline ...
"小组论文分： & \underline{\hspace{5cm}}" newline ...
"\end{tabular}" newline ...
"\end{document}" newline];
writeText(fullfile(projectRoot, 'cover.tex'), content);
end

function writeMergeTex(projectRoot)
content = [
"\documentclass[a4paper]{article}" newline ...
"\usepackage[paper=a4paper,margin=0pt]{geometry}" newline ...
"\usepackage{pdfpages}" newline ...
"\begin{document}" newline ...
"\includepdf[pages=-]{cover.pdf}" newline ...
"\includepdf[pages=-]{report_body.pdf}" newline ...
"\end{document}" newline];
writeText(fullfile(projectRoot, 'merge_report.tex'), content);
end

function writeText(filePath, content)
fid = fopen(filePath, 'w', 'n', 'UTF-8');
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', content);
end
