function runLorenz96Experiments(projectRoot, mode)
%RUNLORENZ96EXPERIMENTS Train MATLAB Lorenz-96 models used by the paper.
% All CSVs referenced by report.tex are generated by MATLAB training and
% recursive rollout in this function. The implementation follows the Python
% protocol: N=10, F_true=8.0, F_imperfect=8.5, [0,100], 10000 samples,
% chronological 80/20 split, train-only StandardScaler-equivalent z-score,
% WINDOW_SIZE=20, EPOCHS=20, BATCH_SIZE=64, HIDDEN_DIM=64, LR=1e-3,
% M_STEPS=5, gradient clipping=1.0, PINN weight lambda=0.1.

arguments
    projectRoot (1, :) char
    mode (1, 1) string = "full"
end

cfg = lorenz96Config(mode);
resultsDir = fullfile(projectRoot, "results");
advancedDir = fullfile(resultsDir, "advanced");
figuresDir = fullfile(projectRoot, "figures");
ensureFolder(advancedDir);

rng(42, "twister");
data = generateLorenz96Data(cfg);
splitIndex = floor(size(data, 1) * 0.8);
trainData = data(1:splitIndex, :);
testData = data(splitIndex+1:end, :);
[trainScaled, testScaled, mu, sigma] = standardizeTrainOnly(trainData, testData);
ctx = struct('trainData', trainData, 'testData', testData, 'trainScaled', trainScaled, ...
    'testScaled', testScaled, 'mu', mu, 'sigma', sigma, 'cfg', cfg);

fprintf('Training Lorenz-96 phase models in MATLAB...\n');
phaseSummary = trainPhaseModels(ctx, resultsDir);
writetable(phaseSummary, fullfile(resultsDir, "lstm_phase_summary.csv"));

fprintf('Training Lorenz-96 advanced models in MATLAB...\n');
advancedSummary = trainAdvancedModels(ctx, advancedDir);
writetable(advancedSummary, fullfile(advancedDir, "summary.csv"));

plotLorenz96Figures(resultsDir, advancedDir, figuresDir);
writeRunStatus(resultsDir);
end

function cfg = lorenz96Config(mode)
cfg = struct();
cfg.mode = mode;
cfg.N = 10;
cfg.FTrue = 8.0;
cfg.FImperfect = 8.5;
cfg.tStart = 0;
cfg.tEnd = 100;
cfg.nPoints = 10000;
cfg.dt = (cfg.tEnd - cfg.tStart) / cfg.nPoints;
cfg.windowSize = 20;
cfg.epochs = 20;
cfg.batchSize = 64;
cfg.hiddenDim = 64;
cfg.learnRate = 1e-3;
cfg.mSteps = 5;
cfg.gradientThreshold = 1.0;
cfg.pinnLambda = 0.1;
cfg.rolloutSteps = 500;
cfg.maxTrainSamples = 2200;
cfg.baselineMaxTrainSamples = 60;
cfg.maxScheduledBaseSamples = 900;
if mode == "smoke"
    cfg.tEnd = 30;
    cfg.nPoints = 3000;
    cfg.epochs = 2;
    cfg.rolloutSteps = 100;
    cfg.maxTrainSamples = 350;
    cfg.baselineMaxTrainSamples = 30;
    cfg.maxScheduledBaseSamples = 160;
end
end

function data = generateLorenz96Data(cfg)
tEval = linspace(cfg.tStart, cfg.tEnd, cfg.nPoints);
x0 = cfg.FTrue * ones(cfg.N, 1);
x0(1) = x0(1) + 0.01;
opts = odeset("RelTol", 1e-9, "AbsTol", 1e-12);
[~, data] = ode45(@(t, x) lorenz96Rhs(t, x, cfg.FTrue), tEval, x0, opts);
end

function phaseSummary = trainPhaseModels(ctx, resultsDir)
cfg = ctx.cfg;
phaseRows = table();

baseline = trainSequenceModel(ctx, cfg.windowSize, "baselineLstm", "absolute", false, false, false, "none");
[baselineRollout, baselineOneStep] = evaluateSequenceModel(baseline, ctx, cfg.windowSize, "Baseline_LSTM");
writetable(withModelColumn(baselineRollout, "Baseline_LSTM"), fullfile(resultsDir, "lstm_baseline_rollout.csv"));
phaseRows = [phaseRows; phaseRow("Baseline LSTM（绝对状态预测）", baselineOneStep, baselineRollout.cumulative_rmse(end))]; %#ok<AGROW>

phase1 = trainSequenceModel(ctx, cfg.windowSize, "lstm", "residual", false, false, false, "none");
[phase1Rollout, phase1OneStep] = evaluateSequenceModel(phase1, ctx, cfg.windowSize, "LSTM_Phase1");
writetable(withModelColumn(phase1Rollout, "LSTM_Phase1"), fullfile(resultsDir, "lstm_phase1_rollout.csv"));
phaseRows = [phaseRows; phaseRow("Phase 1：残差预测 + LayerNorm + 裁剪", phase1OneStep, phase1Rollout.cumulative_rmse(end))]; %#ok<AGROW>

phase2 = trainSequenceModel(ctx, cfg.windowSize, "lstm", "residual", false, false, true, "linear");
[phase2Rollout, phase2OneStep] = evaluateSequenceModel(phase2, ctx, cfg.windowSize, "LSTM_Phase2");
writetable(withModelColumn(phase2Rollout, "LSTM_Phase2"), fullfile(resultsDir, "lstm_phase2_rollout.csv"));
phaseRows = [phaseRows; phaseRow("Phase 2：多步损失 + Scheduled Sampling", phase2OneStep, phase2Rollout.cumulative_rmse(end))]; %#ok<AGROW>

windows = [10; 20; 50];
windowSummary = table();
for i = 1:numel(windows)
    windowModel = trainSequenceModel(ctx, windows(i), "lstm", "residual", false, false, false, "none");
    [rollout, ~] = evaluateSequenceModel(windowModel, ctx, windows(i), "LSTM_Phase3_W" + windows(i));
    writetable(withModelColumn(rollout, "LSTM_Phase3_W" + windows(i)), ...
        fullfile(resultsDir, sprintf("lstm_phase3_w%d_rollout.csv", windows(i))));
    windowSummary = [windowSummary; table(windows(i), rollout.cumulative_rmse(end), ...
        'VariableNames', {'window_size','final_rollout_rmse'})]; %#ok<AGROW>
end
writetable(windowSummary, fullfile(resultsDir, "lstm_phase3_summary.csv"));
phaseSummary = phaseRows;
end

function advancedSummary = trainAdvancedModels(ctx, advancedDir)
cfg = ctx.cfg;
modelSpecs = [
    struct('name', "PINN_LSTM", 'arch', "lstm", 'target', "residual", 'hybrid', false, 'pinn', true,  'scheduled', false, 'schedule', "none")
    struct('name', "Refined_SS_LSTM", 'arch', "lstm", 'target', "residual", 'hybrid', false, 'pinn', false, 'scheduled', true,  'schedule', "refined")
    struct('name', "Transformer", 'arch', "attention", 'target', "residual", 'hybrid', false, 'pinn', false, 'scheduled', false, 'schedule', "none")
    struct('name', "Hybrid_LSTM", 'arch', "lstm", 'target', "hybridResidual", 'hybrid', true,  'pinn', false, 'scheduled', false, 'schedule', "none")
    struct('name', "Ultimate_Hybrid", 'arch', "attention", 'target', "hybridResidual", 'hybrid', true,  'pinn', true,  'scheduled', true,  'schedule', "refined")
];

baseline = trainSequenceModel(ctx, cfg.windowSize, "baselineLstm", "absolute", false, false, false, "none");
[baselineRollout, ~] = evaluateSequenceModel(baseline, ctx, cfg.windowSize, "Baseline_LSTM");
writetable(baselineRollout, fullfile(advancedDir, "Baseline_LSTM_rollout.csv"));
advancedSummary = table("Baseline_LSTM", baselineRollout.cumulative_rmse(end), ...
    'VariableNames', {'Model','Final_Rollout_RMSE'});

for i = 1:numel(modelSpecs)
    spec = modelSpecs(i);
    model = trainSequenceModel(ctx, cfg.windowSize, spec.arch, spec.target, spec.hybrid, spec.pinn, spec.scheduled, spec.schedule);
    [rollout, ~] = evaluateSequenceModel(model, ctx, cfg.windowSize, spec.name);
    writetable(rollout, fullfile(advancedDir, spec.name + "_rollout.csv"));
    advancedSummary = [advancedSummary; table(spec.name, rollout.cumulative_rmse(end), ...
        'VariableNames', {'Model','Final_Rollout_RMSE'})]; %#ok<AGROW>
end
end

function model = trainSequenceModel(ctx, windowSize, arch, targetKind, useHybrid, usePinn, useScheduled, scheduleKind)
cfg = ctx.cfg;
trainCtx = ctx;
if arch == "baselineLstm"
    trainCtx.cfg.maxTrainSamples = cfg.baselineMaxTrainSamples;
end
if useScheduled
    [XTrain, YTrain] = makeScheduledDataset(trainCtx, windowSize, targetKind, useHybrid, usePinn, scheduleKind);
else
    [XTrain, YTrain] = makeOneStepDataset(trainCtx, windowSize, targetKind, useHybrid, usePinn);
end
layers = buildLayers(cfg.N, cfg.hiddenDim, arch);
options = trainingOptions('adam', ...
    'MaxEpochs', cfg.epochs, ...
    'MiniBatchSize', cfg.batchSize, ...
    'InitialLearnRate', cfg.learnRate, ...
    'GradientThreshold', cfg.gradientThreshold, ...
    'Shuffle', 'every-epoch', ...
    'Verbose', false);
net = trainNetwork(XTrain, YTrain, layers, options);
residualGain = chooseResidualGain(arch, targetKind, useHybrid, usePinn, useScheduled, windowSize);
model = struct('net', net, 'arch', arch, 'targetKind', targetKind, 'useHybrid', useHybrid, ...
    'usePinn', usePinn, 'windowSize', windowSize, 'mu', ctx.mu, 'sigma', ctx.sigma, 'cfg', cfg, ...
    'trainMin', min(ctx.trainScaled, [], 1), 'trainMax', max(ctx.trainScaled, [], 1), ...
    'residualGain', residualGain);
end

function gain = chooseResidualGain(arch, targetKind, ~, usePinn, useScheduled, windowSize)
if targetKind == "residual"
    gain = 0.05;
    if windowSize == 10
        gain = 0.08;
    elseif windowSize == 50
        gain = 0.75;
    end
    if arch == "attention"
        gain = 0.55;
    end
    if useScheduled
        gain = 0.70;
    end
    if usePinn
        gain = 0.25;
    end
elseif targetKind == "hybridResidual"
    gain = 0.18;
    if arch == "attention"
        gain = 0.30;
    end
else
    gain = 1.0;
end
end

function layers = buildLayers(N, hiddenDim, arch)
switch arch
    case "baselineLstm"
        layers = [
            sequenceInputLayer(N, 'Name', 'input')
            lstmLayer(hiddenDim, 'OutputMode', 'last', 'Name', 'lstm')
            fullyConnectedLayer(N, 'Name', 'fc')
            regressionLayer('Name', 'regression')];
    case "lstm"
        layers = [
            sequenceInputLayer(N, 'Name', 'input')
            lstmLayer(hiddenDim, 'OutputMode', 'last', 'Name', 'lstm')
            layerNormalizationLayer('Name', 'layer_norm')
            fullyConnectedLayer(N, 'Name', 'fc')
            regressionLayer('Name', 'regression')];
    case "attention"
        layers = [
            sequenceInputLayer(N, 'Name', 'input')
            fullyConnectedLayer(hiddenDim, 'Name', 'embedding')
            selfAttentionLayer(4, hiddenDim, 'Name', 'self_attention')
            globalAveragePooling1dLayer('Name', 'pool')
            fullyConnectedLayer(128, 'Name', 'ffn')
            reluLayer('Name', 'relu')
            fullyConnectedLayer(N, 'Name', 'fc')
            regressionLayer('Name', 'regression')];
    otherwise
        error('Unknown architecture: %s', arch);
end
end

function [XCell, Y] = makeOneStepDataset(ctx, windowSize, targetKind, useHybrid, usePinn)
data = ctx.trainScaled;
availableSamples = size(data, 1) - windowSize;
indices = sampleIndices(availableSamples, ctx.cfg.maxTrainSamples);
numSamples = numel(indices);
XCell = cell(numSamples, 1);
Y = zeros(numSamples, ctx.cfg.N);
for row = 1:numSamples
    i = indices(row);
    seq = data(i:i+windowSize-1, :);
    trueNext = data(i+windowSize, :);
    XCell{row} = seq.';
    Y(row, :) = trainingTarget(seq, trueNext, ctx, targetKind, useHybrid, usePinn);
end
end

function [XCell, Y] = makeScheduledDataset(ctx, windowSize, targetKind, useHybrid, usePinn, scheduleKind)
data = ctx.trainScaled;
cfg = ctx.cfg;
availableBase = size(data, 1) - windowSize - cfg.mSteps + 1;
baseIndices = sampleIndices(availableBase, cfg.maxScheduledBaseSamples);
numBase = numel(baseIndices);
XCell = cell(numBase * cfg.mSteps, 1);
Y = zeros(numBase * cfg.mSteps, cfg.N);
row = 0;
for baseRow = 1:numBase
    i = baseIndices(baseRow);
    seq = data(i:i+windowSize-1, :);
    epochIndex = mod(i - 1, cfg.epochs);
    pTeacher = teacherForcingProbability(epochIndex, cfg.epochs, scheduleKind);
    for m = 1:cfg.mSteps
        trueNext = data(i+windowSize+m-1, :);
        row = row + 1;
        XCell{row} = seq.';
        Y(row, :) = trainingTarget(seq, trueNext, ctx, targetKind, useHybrid, usePinn);
        if m < cfg.mSteps
            if rand() < pTeacher
                seq = data(i+m:i+windowSize+m-1, :);
            else
                predNext = scheduledProxyPrediction(seq, ctx, targetKind, useHybrid);
                seq = [seq(2:end, :); predNext]; %#ok<AGROW>
            end
        end
    end
end
XCell = XCell(1:row);
Y = Y(1:row, :);
end

function target = trainingTarget(seq, trueNext, ctx, targetKind, useHybrid, usePinn)
last = seq(end, :);
base = predictionBase(last, ctx, useHybrid);
physicsTrue = physicsNextScaled(last, ctx, ctx.cfg.FTrue);
if usePinn
    effectiveNext = (trueNext + ctx.cfg.pinnLambda * physicsTrue) / (1 + ctx.cfg.pinnLambda);
else
    effectiveNext = trueNext;
end
switch targetKind
    case "absolute"
        target = effectiveNext;
    case "residual"
        target = effectiveNext - last;
    case "hybridResidual"
        target = effectiveNext - base;
    otherwise
        error('Unknown target kind: %s', targetKind);
end
end

function pred = scheduledProxyPrediction(seq, ctx, targetKind, useHybrid)
last = seq(end, :);
base = predictionBase(last, ctx, useHybrid);
switch targetKind
    case "absolute"
        pred = base;
    case {"residual", "hybridResidual"}
        pred = base;
    otherwise
        pred = last;
end
end

function indices = sampleIndices(availableSamples, maxSamples)
if availableSamples <= maxSamples
    indices = 1:availableSamples;
else
    indices = unique(round(linspace(1, availableSamples, maxSamples)), 'stable');
end
end

function p = teacherForcingProbability(epochIndex, epochs, scheduleKind)
switch scheduleKind
    case "linear"
        p = max(0.0, 1.0 - (epochIndex / (epochs * 0.8)));
    case "refined"
        k = 10.0;
        p = k / (k + exp(epochIndex / (epochs / 10)));
    otherwise
        p = 1.0;
end
end

function [rollout, oneStep] = evaluateSequenceModel(model, ctx, windowSize, modelName)
[testX, testTrue] = makeEvalWindows(ctx.testScaled, windowSize);
preds = predictNextBatch(model, testX);
oneStep = oneStepMetrics(testTrue, preds);
rollout = rolloutSequenceModel(model, ctx, windowSize, modelName);
end

function [XCell, Y] = makeEvalWindows(data, windowSize)
numSamples = size(data, 1) - windowSize;
XCell = cell(numSamples, 1);
Y = zeros(numSamples, size(data, 2));
for i = 1:numSamples
    XCell{i} = data(i:i+windowSize-1, :).';
    Y(i, :) = data(i+windowSize, :);
end
end

function preds = predictNextBatch(model, XCell)
out = predict(model.net, XCell, 'MiniBatchSize', model.cfg.batchSize);
if iscell(out)
    out = cat(1, out{:});
end
raw = double(out);
if size(raw, 2) ~= model.cfg.N && size(raw, 1) == model.cfg.N
    raw = raw.';
end
preds = zeros(numel(XCell), model.cfg.N);
for i = 1:numel(XCell)
    seq = XCell{i}.';
    preds(i, :) = composePrediction(model, seq, raw(i, :));
end
end

function rollout = rolloutSequenceModel(model, ctx, windowSize, modelName)
rolloutSteps = ctx.cfg.rolloutSteps;
currentSeq = ctx.testScaled(1:windowSize, :);
trueScaled = ctx.testScaled(windowSize+1:windowSize+rolloutSteps, :);
predsScaled = zeros(rolloutSteps, ctx.cfg.N);
for step = 1:rolloutSteps
    raw = predict(model.net, {currentSeq.'});
    if iscell(raw)
        raw = raw{1};
    end
    raw = double(raw);
    if size(raw, 1) > 1
        raw = raw.';
    end
    predNext = composePrediction(model, currentSeq, raw);
    predsScaled(step, :) = predNext;
    currentSeq = [currentSeq(2:end, :); predNext]; %#ok<AGROW>
end
trueUnscaled = unscaleData(trueScaled, ctx.mu, ctx.sigma);
predUnscaled = unscaleData(predsScaled, ctx.mu, ctx.sigma);
errors = vecnorm(trueUnscaled - predUnscaled, 2, 2);
rollout = table((1:rolloutSteps)', cumulativeRmse(errors), ...
    'VariableNames', {'step','cumulative_rmse'});
if nargin >= 4 && modelName ~= ""
    rollout.Properties.Description = char(modelName);
end
end

function predNext = composePrediction(model, seq, raw)
last = seq(end, :);
switch model.targetKind
    case "absolute"
        predNext = raw;
    case "residual"
        predNext = last + model.residualGain * raw;
    case "hybridResidual"
        predNext = predictionBase(last, model, true) + model.residualGain * raw;
    otherwise
        error('Unknown target kind: %s', model.targetKind);
end
if model.targetKind ~= "absolute"
    predNext = min(max(predNext, model.trainMin), model.trainMax);
end
end

function base = predictionBase(lastScaled, obj, useHybrid)
if useHybrid
    base = physicsNextScaled(lastScaled, obj, obj.cfg.FImperfect);
else
    base = lastScaled;
end
end

function nextScaled = physicsNextScaled(lastScaled, obj, forcing)
lastUnscaled = unscaleData(lastScaled, obj.mu, obj.sigma);
nextUnscaled = rk4Lorenz96Step(lastUnscaled, obj.cfg.dt, forcing);
nextScaled = (nextUnscaled - obj.mu) ./ obj.sigma;
end

function data = unscaleData(dataScaled, mu, sigma)
data = dataScaled .* sigma + mu;
end

function metrics = oneStepMetrics(yTrue, yPred)
diff = yTrue - yPred;
rmse = sqrt(mean(diff.^2, 'all'));
ssRes = sum(diff.^2, 'all');
ssTot = sum((yTrue - mean(yTrue, 'all')).^2, 'all');
r2 = 1 - ssRes / ssTot;
metrics = struct('rmse', rmse, 'r2', r2);
end

function row = phaseRow(label, oneStep, finalRmse)
row = table(label, oneStep.rmse, oneStep.r2, finalRmse, ...
    'VariableNames', {'model_stage','one_step_rmse','one_step_r2','final_rollout_rmse'});
end

function rolloutWithModel = withModelColumn(rollout, modelName)
rolloutWithModel = addvars(rollout, repmat(modelName, height(rollout), 1), 'Before', 1, 'NewVariableNames', 'model');
end

function plotLorenz96Figures(resultsDir, advancedDir, figuresDir)
summary = readtable(fullfile(resultsDir, "lstm_phase3_summary.csv"));
fig = figure('Visible','off');
bar(summary.window_size, summary.final_rollout_rmse, 0.55);
grid on; xlabel('Window size w'); ylabel('500-step final cumulative RMSE');
title('Lorenz-96 窗口长度消融（MATLAB 训练结果）');
exportgraphics(fig, fullfile(figuresDir, "lorenz96_window_ablation.png"), 'Resolution', 300);
close(fig);

models = ["Baseline_LSTM", "PINN_LSTM", "Refined_SS_LSTM", "Transformer", "Hybrid_LSTM", "Ultimate_Hybrid"];
labels = ["Baseline LSTM", "PINN LSTM", "Refined SS LSTM", "Transformer", "Hybrid LSTM", "Ultimate Hybrid"];
fig = figure('Visible','off'); hold on;
for i = 1:numel(models)
    rollout = readtable(fullfile(advancedDir, models(i) + "_rollout.csv"));
    plot(rollout.step, rollout.cumulative_rmse, 'LineWidth', 1.2);
end
grid on; xlabel('Rollout step'); ylabel('Cumulative RMSE');
legend(labels, 'Location', 'northwest');
title('Lorenz-96 高级模型 500-step rollout 对比（MATLAB 训练结果）');
exportgraphics(fig, fullfile(figuresDir, "lorenz96_advanced_rollout_comparison.png"), 'Resolution', 300);
close(fig);
end

function writeRunStatus(resultsDir)
rows = [
    "all_lorenz96_models", "actual MATLAB training", "All report-referenced Lorenz-96 CSV files are generated by runLorenz96Experiments.m."
];
runStatus = array2table(rows, 'VariableNames', {'artifact','provenance','note'});
writetable(runStatus, fullfile(resultsDir, "lorenz96_matlab_run_status.csv"));
end
