function runLorenz96Experiments(projectRoot, mode)
%RUNLORENZ96EXPERIMENTS MATLAB Lorenz-96 data protocol and real baseline training.
% The full advanced Lorenz-96 table in the paper is retained as original
% paper reference output. This function no longer fabricates rollout curves:
% it generates the Lorenz-96 trajectory, performs the chronological split and
% train-only scaling, trains a real MATLAB residual LSTM baseline, and writes
% its actual 500-step rollout to results/matlab_lorenz96_residual_lstm_*.csv.

arguments
    projectRoot (1, :) char
    mode (1, 1) string = "full"
end

resultsDir = fullfile(projectRoot, "results");
advancedDir = fullfile(resultsDir, "advanced");
figuresDir = fullfile(projectRoot, "figures");
ensureFolder(advancedDir);

rng(42, "twister");
N = 10;
FTrue = 8.0;
tStart = 0;
tEnd = 100;
nPoints = 10000;
tEval = linspace(tStart, tEnd, nPoints);
x0 = FTrue * ones(N, 1);
x0(1) = x0(1) + 0.01;
opts = odeset("RelTol", 1e-9, "AbsTol", 1e-12);
if mode == "smoke"
    tEval = linspace(tStart, 20, 2500);
end
[~, data] = ode45(@(t, x) lorenz96Rhs(t, x, FTrue), tEval, x0, opts);

splitIndex = floor(size(data, 1) * 0.8);
trainData = data(1:splitIndex, :);
testData = data(splitIndex+1:end, :);
[trainScaled, testScaled, mu, sigma] = standardizeTrainOnly(trainData, testData);

statusRows = strings(0, 3);
try
    actual = trainAndRolloutResidualLstm(trainScaled, testScaled, mu, sigma, mode);
    writetable(actual.rollout, fullfile(resultsDir, "matlab_lorenz96_residual_lstm_rollout.csv"));
    writetable(actual.summary, fullfile(resultsDir, "matlab_lorenz96_residual_lstm_summary.csv"));
    statusRows(end+1, :) = ["matlab_lorenz96_residual_lstm", "actual MATLAB training", "Residual LSTM trained with trainNetwork; output is separate from original paper reference tables."];
catch exception
    warning("Residual LSTM training failed: %s", exception.message);
    actual = trainAndRolloutResidualLinear(trainScaled, testScaled, mu, sigma);
    writetable(actual.rollout, fullfile(resultsDir, "matlab_lorenz96_residual_linear_rollout.csv"));
    writetable(actual.summary, fullfile(resultsDir, "matlab_lorenz96_residual_linear_summary.csv"));
    statusRows(end+1, :) = ["matlab_lorenz96_residual_linear", "actual MATLAB fallback training", "Residual linear fallback used because residual LSTM training failed."];
end

statusRows(end+1, :) = ["lstm_phase1/2/3 and advanced CSVs", "original paper reference", "Retained from the main-branch paper outputs; not regenerated by this MATLAB function."];
runStatus = array2table(statusRows, 'VariableNames', {'artifact','provenance','note'});
writetable(runStatus, fullfile(resultsDir, "lorenz96_matlab_run_status.csv"));

plotLorenz96ReferenceFigures(resultsDir, advancedDir, figuresDir);
end

function actual = trainAndRolloutResidualLstm(trainScaled, testScaled, mu, sigma, mode)
windowSize = 20;
rolloutSteps = 500;
hiddenDim = 64;
epochs = 20;
if mode == "smoke"
    epochs = 2;
end
[XTrain, YTrainDelta] = makeSequenceDataset(trainScaled, windowSize);
N = size(trainScaled, 2);
layers = [
    sequenceInputLayer(N, 'Name', 'input')
    lstmLayer(hiddenDim, 'OutputMode', 'last', 'Name', 'lstm')
    layerNormalizationLayer('Name', 'layer_norm')
    fullyConnectedLayer(N, 'Name', 'fc')
    regressionLayer('Name', 'regression')];
options = trainingOptions('adam', ...
    'MaxEpochs', epochs, ...
    'MiniBatchSize', 64, ...
    'InitialLearnRate', 1e-3, ...
    'GradientThreshold', 1.0, ...
    'Shuffle', 'every-epoch', ...
    'Verbose', false);
net = trainNetwork(XTrain, YTrainDelta, layers, options);
rollout = rolloutResidualPredictor(@(seq) predictResidualLstm(net, seq), testScaled, mu, sigma, windowSize, rolloutSteps, "MATLAB_Residual_LSTM");
summary = table("MATLAB_Residual_LSTM", rollout.cumulative_rmse(end), ...
    'VariableNames', {'Model','Final_Rollout_RMSE'});
actual = struct('rollout', rollout, 'summary', summary);
end

function actual = trainAndRolloutResidualLinear(trainScaled, testScaled, mu, sigma)
windowSize = 20;
rolloutSteps = 500;
[XTrain, YTrainDelta] = makeFlatWindowDataset(trainScaled, windowSize);
linear = [ones(size(XTrain, 1), 1), XTrain] \ YTrainDelta;
predictor = @(seq) [1, reshape(seq.', 1, [])] * linear;
rollout = rolloutResidualPredictor(predictor, testScaled, mu, sigma, windowSize, rolloutSteps, "MATLAB_Residual_Linear");
summary = table("MATLAB_Residual_Linear", rollout.cumulative_rmse(end), ...
    'VariableNames', {'Model','Final_Rollout_RMSE'});
actual = struct('rollout', rollout, 'summary', summary);
end

function [XCell, YDelta] = makeSequenceDataset(data, windowSize)
numSamples = size(data, 1) - windowSize;
XCell = cell(numSamples, 1);
YDelta = zeros(numSamples, size(data, 2));
for i = 1:numSamples
    seq = data(i:i+windowSize-1, :);
    XCell{i} = seq.';
    YDelta(i, :) = data(i+windowSize, :) - data(i+windowSize-1, :);
end
end

function [XFlat, YDelta] = makeFlatWindowDataset(data, windowSize)
numSamples = size(data, 1) - windowSize;
N = size(data, 2);
XFlat = zeros(numSamples, windowSize * N);
YDelta = zeros(numSamples, N);
for i = 1:numSamples
    seq = data(i:i+windowSize-1, :);
    XFlat(i, :) = reshape(seq.', 1, []);
    YDelta(i, :) = data(i+windowSize, :) - data(i+windowSize-1, :);
end
end

function delta = predictResidualLstm(net, seq)
delta = predict(net, {seq.'});
if iscell(delta)
    delta = delta{1};
end
delta = double(delta);
if size(delta, 1) > 1
    delta = delta.';
end
end

function rollout = rolloutResidualPredictor(predictor, testScaled, mu, sigma, windowSize, rolloutSteps, modelName)
currentSeq = testScaled(1:windowSize, :);
trueScaled = testScaled(windowSize+1:windowSize+rolloutSteps, :);
predsScaled = zeros(rolloutSteps, size(testScaled, 2));
for step = 1:rolloutSteps
    delta = predictor(currentSeq);
    predNext = currentSeq(end, :) + delta;
    predsScaled(step, :) = predNext;
    currentSeq = [currentSeq(2:end, :); predNext]; %#ok<AGROW>
end
trueUnscaled = trueScaled .* sigma + mu;
predUnscaled = predsScaled .* sigma + mu;
errors = vecnorm(trueUnscaled - predUnscaled, 2, 2);
rollout = table(repmat(modelName, rolloutSteps, 1), (1:rolloutSteps)', errors, cumulativeRmse(errors), ...
    'VariableNames', {'model','step','state_error','cumulative_rmse'});
end

function plotLorenz96ReferenceFigures(resultsDir, advancedDir, figuresDir)
summaryFile = fullfile(resultsDir, "lstm_phase3_summary.csv");
if isfile(summaryFile)
    summary = readtable(summaryFile);
    fig = figure('Visible','off');
    bar(summary.window_size, summary.final_rollout_rmse, 0.55);
    grid on; xlabel('Window size w'); ylabel('500-step final cumulative RMSE');
    title('Lorenz-96 窗口长度消融（原论文参考结果）');
    exportgraphics(fig, fullfile(figuresDir, "lorenz96_window_ablation.png"), 'Resolution', 300);
    close(fig);
end

models = ["Baseline_LSTM", "PINN_LSTM", "Refined_SS_LSTM", "Transformer", "Hybrid_LSTM", "Ultimate_Hybrid"];
labels = ["Baseline LSTM", "PINN LSTM", "Refined SS LSTM", "Transformer", "Hybrid LSTM", "Ultimate Hybrid"];
if all(isfile(fullfile(advancedDir, models + "_rollout.csv")))
    fig = figure('Visible','off'); hold on;
    for i = 1:numel(models)
        rollout = readtable(fullfile(advancedDir, models(i) + "_rollout.csv"));
        plot(rollout.step, rollout.cumulative_rmse, 'LineWidth', 1.2);
    end
    grid on; xlabel('Rollout step'); ylabel('Cumulative RMSE');
    legend(labels, 'Location', 'northwest');
    title('Lorenz-96 高级模型 500-step rollout 对比（原论文参考结果）');
    exportgraphics(fig, fullfile(figuresDir, "lorenz96_advanced_rollout_comparison.png"), 'Resolution', 300);
    close(fig);
end
end
